# Specify output directory - either absolute path or relative to Snakefile.
# If using relative paths for subsequent files, these should be relative to
# this workding directory.
workdir: example/analysis/

tmpdir: example/analysis/

data:  ../config/samples.tsv

fastqScreen: ../config/fastq_screen.config

sample: 0
paired: False
strand: R

genome:
    build: BDGP6
    transcriptome:
        - ../genome/Drosophila_melanogaster.BDGP6.32.cdna.all.fa.gz
        - ../genome/Drosophila_melanogaster.BDGP6.32.ncrna.fa.gz
    index: ../genome/index/BDGP6_tran
    gff3: ../genome/Drosophila_melanogaster.BDGP6.32.104.gff3.gz

cutadapt:
    forwardAdapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
    reverseAdapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
    overlap:        3
    errorRate:      0.1
    minimumLength:  1
    qualityCutoff:  0,0
    GCcontent:      43


misc:
    inferExperimentSampleSize: 75000 # Reduce for downsampled dataset

QConly: False

multiQCconfig: ../config/multiqc_config.yaml
