data : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/RNA-Seq/config/samples.csv

genome : /media/stephen/Data/genomes/GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz

build : GRCm38

annotation : /media/stephen/Data/genomes/GRCm38/annotation/Mus_musculus.GRCm38.99.gtf

outdir : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/RNA-Seq/analysis

fastq_screen_config : /media/stephen/Data/20120810_LewisS_AM_MMhmeDIP/RNA-Seq/config/fastq_screen.config
